app = "terrateam-malcolm-blimpup-test-app"
kill_signal = "SIGINT"
kill_timeout = 30

[build]
  image = "flyio/hellofly:latest"

[[services]]
  internal_port = 4000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 100
    soft_limit = 30
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "3s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"