engine:
  name: terraform
hooks:
  all:
    pre:
    - type: run
      cmd: ['bash', '-c', '${TERRATEAM_TF_CMD} --version | grep 1\.5\.7']
    - cmd:
      - test
      - ${TERRATEAM_TF_CMD}
      - '='
      - terraform
      type: run
