default_tf_version: 1.5.0
hooks:
  all:
    pre:
    - cmd:
      - test
      - ${TERRATEAM_TF_CMD}
      - '='
      - terraform
      type: run
    - cmd:
      - bash
      - -c
      - ${TERRATEAM_TF_CMD} --version | grep "Terraform v1\.5\.0"
      type: run
