engine:
  name: tofu
workflows:
- apply:
  - cmd:
    - echo
    - FOO
    name: BAR
    type: env
  - cmd:
    - sh
    - -c
    - exit 1
    type: run
  - capture_output: true
    cmd:
    - ${TERRATEAM_ROOT}/expect-env
    - BAR
    run_on: failure
    type: run
  - type: init
  - type: apply
  plan:
  - cmd:
    - echo
    - FOO
    name: BAR
    type: env
  - cmd:
    - sh
    - -c
    - exit 1
    type: run
  - capture_output: true
    cmd:
    - ${TERRATEAM_ROOT}/expect-env
    - BAR
    run_on: failure
    type: run
  - type: init
  - type: plan
  tag_query: ''
